
image: docker:20.10.16

services:
  - docker:20.10.16-dind

before_script:
  - docker info
  
stages: 
#  - build
  - test

#build-job: 
  #stage: build
  #script:
 #   - echo "Compiling the code..."
#    - docker-compose build --no-cache
#    - docker-compose up -d
#    - sleep 20
#    - docker-compose down
#    - echo "Compile complete."


test-job:
  stage: test
  script:
    - echo "Test stage starting"
    #- docker-compose build --no-cache
    - docker-compose --profile test up -d --build
    - sleep 120
    - docker-compose logs --since 2m tests
    - sleep 20
    - docker-compose logs --since 2m tests
    - docker-compose logs --since 2m original
    - STR=$(docker-compose logs --since 2m tests)
    - FAILED='test failed'
    - docker-compose down
    - if [[ "$STR" == *"$FAILED"* ]]; then echo "PIPELINE FAILED" exit 1; fi
    - if [[ "$STR" == *"$FAILED"* ]]; then exit 1; fi
    - echo "Test stage done"



